brew "bat"
brew "eza"
brew "fish"
brew "fzf"
brew "git"
brew "go"
brew "httpie"
brew "luarocks"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "font-jetbrains-mono-nerd-font"
cask "wezterm"

go "github.com/rhysd/vim-startuptime"
